<a href="https://colab.research.google.com/github/KartikMalik1470/Pytorch/blob/main/linear_regression_with_PyTorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Step 1 - import numpy and torch

In [ ]:
import numpy as np
import torch

###Step 2 - take the inputs as an array (temp, rainfall, humidity)

In [ ]:
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype = 'float32')

In [ ]:
inputs.dtype

dtype('float32')

###Step 3 -take the outputs as an array too output (apples, oranges)

In [ ]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype = 'float32')

In [ ]:
targets.dtype

dtype('float32')

### Step 4 -convert inputs and targets to tensors using torch.from_numpy

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


###Step 5 - initializing weigths and biases

In [ ]:
w = torch.randn(2, 3, requires_grad = True )
b = torch.randn(2, requires_grad = True)

# randn generates random numbers from a standard normal distribution mean = 0 and standard deviation = 1.
# random generates random numbers from a uniform distribution between 0 and 1.


In [ ]:
print(w)
print(b)

tensor([[ 0.2631, -1.3545, -0.2837],
        [ 0.5097, -0.1013,  0.2835]], requires_grad=True)
tensor([-0.3706,  0.2713], requires_grad=True)


###Step 6 -Now we made the model function in this and basically the formulae is = w*x +b

In [ ]:
def model(x):
  return x @ w.t() + b

###Step 6 - Now generate the predictions

In [ ]:
preds = model(inputs)
preds

tensor([[ -84.1125,   42.8820],
        [-113.7781,   55.8829],
        [-175.4367,   47.4851],
        [ -42.2709,   58.3912],
        [-132.1053,   45.5616]], grad_fn=<AddBackward0>)

###Step 7 - Now compare with targets

In [ ]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
def mse(y1, y2):
  diff = y1 - y2
  return torch.sum(diff*diff/diff.numel())

  # the numel() method of a tensor returns the number of elements in a tensor

### Step 8 -Compute the loss

In [ ]:
loss = mse(preds, targets)
print(loss)

tensor(21960.2754, grad_fn=<SumBackward0>)


### Step 9 - now apply backward function to the loss value for **backward propogation**

In [ ]:
loss.backward()

In [ ]:
# gradients for weights
print(w)
print(w.grad)

tensor([[ 0.2631, -1.3545, -0.2837],
        [ 0.5097, -0.1013,  0.2835]], requires_grad=True)
tensor([[-15269.3828, -18263.2578, -10880.6729],
        [ -3282.0818,  -4675.2935,  -2672.5283]])


In [ ]:
w
w.grad

tensor([[-15269.3828, -18263.2578, -10880.6729],
        [ -3282.0818,  -4675.2935,  -2672.5283]])

In [ ]:
#adjusting the weights and biases
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [ ]:
loss = mse(preds, targets)
print(loss)

tensor(21960.2754, grad_fn=<SumBackward0>)


In [ ]:
# .zero_() method is used to reset the value of the gradients
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
#generate predictions
preds = model(inputs)
print(preds)

tensor([[ -56.0489,   49.5600],
        [ -76.8458,   64.6947],
        [-131.3669,   58.1559],
        [ -14.8152,   64.7385],
        [ -96.4184,   54.1857]], grad_fn=<AddBackward0>)


In [ ]:
# calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(15358.4746, grad_fn=<SumBackward0>)


In [ ]:
# compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-12368.0977, -15134.8203,  -8952.5938],
        [ -2590.0386,  -3924.5740,  -2210.8181]])
tensor([-151.2991,  -33.7330])


In [ ]:
# now adjust weights and rest gradients
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[ 0.5395, -1.0205, -0.0853],
        [ 0.5684, -0.0153,  0.3323]], requires_grad=True)
tensor([-0.3673,  0.2721], requires_grad=True)


In [ ]:
#calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(10902.5859, grad_fn=<SumBackward0>)


#### Now train this for multiple epocs lets say a 100

In [ ]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
# Now calculate loss again
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(494.8700, grad_fn=<SumBackward0>)


In [ ]:
print(preds)

tensor([[ 65.5692,  75.8035],
        [ 87.1680, 101.9803],
        [ 93.8980, 121.1465],
        [ 70.2098,  68.4443],
        [ 81.8097, 103.1297]], grad_fn=<AddBackward0>)


In [ ]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(144.2639, grad_fn=<SumBackward0>)


In [ ]:
print(preds)

tensor([[ 61.6552,  73.3601],
        [ 84.2869, 100.3477],
        [106.7429, 128.7876],
        [ 47.4401,  54.2467],
        [ 90.0844, 108.5743]], grad_fn=<AddBackward0>)


In [ ]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### Linear regression using PyTorch built-ins

In [ ]:
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                   dtype = 'float32')

In [ ]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype = 'float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

### Dataset & DataLoader
**DataSet** - It's like putting your data into two separate boxes (tensors).
The first box (inputs) contains the information you want the computer to learn from (like images or numbers).
The second box (targets) contains the correct answers or labels that you want the computer to learn to predict

**DataLoader** - A data loader is like a helper that takes your big pile of data, divides it into small groups (batches), and hands those batches to your learning machine one at a time. This makes it easier for your machine to learn from the data without getting overwhelmed and helps it learn efficiently.

we'll create a TensorDataset, which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
# define dataset
# the TensorDataset allows us to access a small section of the training data using the array indexing notation ([0:3] in the above code). it returns a tuple with 2 elements.
# we'll also create a DataLoader, which can split the data into batches of a predefinedsize while training
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
#Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

In [ ]:
for xb, yb in train_dl:
  print(xb)
  print(yb)

tensor([[ 92.,  87.,  64.],
        [ 91.,  87.,  65.],
        [ 73.,  66.,  44.],
        [ 73.,  67.,  43.],
        [ 88., 134.,  59.]])
tensor([[ 82., 100.],
        [ 80., 102.],
        [ 57.,  69.],
        [ 56.,  70.],
        [118., 132.]])
tensor([[103.,  43.,  36.],
        [ 74.,  66.,  43.],
        [102.,  43.,  37.],
        [ 87., 135.,  57.],
        [ 68.,  97.,  70.]])
tensor([[ 20.,  38.],
        [ 57.,  69.],
        [ 22.,  37.],
        [118., 134.],
        [102., 120.]])
tensor([[ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 68.,  96.,  71.],
        [101.,  44.,  37.]])
tensor([[119., 133.],
        [103., 119.],
        [ 81., 101.],
        [104., 118.],
        [ 21.,  38.]])


### nn.linear

In [ ]:
# instead of intializing the weights and biases manually, we can define the model using the nn.linear class from PyTorch, which does it automatically.
# Define Model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1067, -0.3128,  0.0030],
        [-0.5238,  0.0696, -0.1359]], requires_grad=True)
Parameter containing:
tensor([-0.3015, -0.1071], requires_grad=True)


In [ ]:
#the .parameters method returns a list containing all the weights and bias matrices present in the model
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1067, -0.3128,  0.0030],
         [-0.5238,  0.0696, -0.1359]], requires_grad=True),
 Parameter containing:
 tensor([-0.3015, -0.1071], requires_grad=True)]

In [ ]:
# now for generating predections
preds = model(inputs)
preds

tensor([[-13.3338, -39.5220],
        [-17.9166, -50.3420],
        [-32.7489, -44.2287],
        [ -2.7506, -55.5668],
        [-22.7486, -39.0776],
        [-12.9144, -40.1154],
        [-17.6008, -50.5475],
        [-32.6391, -44.8884],
        [ -3.1701, -54.9734],
        [-22.8523, -38.6897],
        [-13.0180, -39.7275],
        [-17.4971, -50.9354],
        [-33.0647, -44.0232],
        [ -2.6469, -55.9546],
        [-23.1681, -38.4842]], grad_fn=<AddmmBackward0>)

In [ ]:
#import nn.functional(it contains many useful loss functions such as mse rmse)
import torch.nn.functional as F

In [ ]:
# for calculating loss we can use the built-in loss function mse_loss instead of typing the whole formulae
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(15379.9346, grad_fn=<MseLossBackward0>)


In [ ]:
#instead of manually manipulating the model's weights and biases using gradients, we can use the optimizer optim.SGD (SGD - stochastic gradient descent)
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

### We are now ready to train the model

In [ ]:
def fit(num_epochs, model, loss_fn, opt, train_dl):

  for epoch in range(num_epochs):

    for inputs, targets in train_dl:

      pred = model(inputs)

      loss = loss_fn(pred, targets)

      loss.backward()

      opt.step()

      opt.zero_grad()

    if (epoch+1) % 10 == 0:
      print(f'Epoch [{epoch+1}/{num_epochs}], Loss: loss.items{loss.item():.4f}') #get 10 numerical values of the loss function



Some things to note above:

* We use the data loader defined earlier to get batches of data for every iteration.

* Instead of updating parameters (weights and biases) manually, we use `opt.step` to perform the update and `opt.zero_grad` to reset the gradients to zero.

* We've also added a log statement that prints the loss from the last batch of data for every 10th epoch to track training progress. `loss.item` returns the actual value stored in the loss tensor.

Let's train the model for 100 `epochs`.

In [ ]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: loss.items317.8008
Epoch [20/100], Loss: loss.items265.3327
Epoch [30/100], Loss: loss.items168.3259
Epoch [40/100], Loss: loss.items123.7542
Epoch [50/100], Loss: loss.items90.4093
Epoch [60/100], Loss: loss.items84.4912
Epoch [70/100], Loss: loss.items50.2473
Epoch [80/100], Loss: loss.items38.6207
Epoch [90/100], Loss: loss.items35.2650
Epoch [100/100], Loss: loss.items16.4730


In [ ]:
preds = model(inputs)
preds

tensor([[ 58.4197,  71.0849],
        [ 81.4386,  97.6473],
        [117.0685, 137.8066],
        [ 29.5785,  41.8837],
        [ 95.6639, 111.0746],
        [ 57.3816,  70.0162],
        [ 81.0916,  97.1954],
        [117.3164, 138.1290],
        [ 30.6166,  42.9523],
        [ 96.3550, 111.6914],
        [ 58.0727,  70.6330],
        [ 80.4004,  96.5787],
        [117.4154, 138.2585],
        [ 28.8873,  41.2669],
        [ 96.7020, 112.1433]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[55.1799, 67.5742]], grad_fn=<AddmmBackward0>)

###conclusion - the yield for apples was 55.1 ton and for oranges it's 67.5 tons